# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_linux64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_linux64)
  main_config = debug_linux64
endif
ifeq ($(config),debug_linux32)
  main_config = debug_linux32
endif
ifeq ($(config),debug_win64)
  main_config = debug_win64
endif
ifeq ($(config),debug_win32)
  main_config = debug_win32
endif
ifeq ($(config),release_linux64)
  main_config = release_linux64
endif
ifeq ($(config),release_linux32)
  main_config = release_linux32
endif
ifeq ($(config),release_win64)
  main_config = release_win64
endif
ifeq ($(config),release_win32)
  main_config = release_win32
endif

PROJECTS := main

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

main:
ifneq (,$(main_config))
	@echo "==== Building main ($(main_config)) ===="
	@${MAKE} --no-print-directory -C . -f main.make config=$(main_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f main.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_linux64"
	@echo "  debug_linux32"
	@echo "  debug_win64"
	@echo "  debug_win32"
	@echo "  release_linux64"
	@echo "  release_linux32"
	@echo "  release_win64"
	@echo "  release_win32"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   main"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"